<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Update</name>
   <tag></tag>
   <elementGuidId>159fa559-452e-4054-b7b6-0e4c660b0249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='console']/div/ul/li[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>20e7b7bf-78a0-409c-b5d0-6db61b3f82e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>put</value>
      <webElementGuid>3e28a140-f798-471b-9d07-222ebb6565e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>endpoint</value>
      <webElementGuid>cc3c6e00-53f8-4add-a6fc-9ee50190fa2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-http</name>
      <type>Main</type>
      <value>put</value>
      <webElementGuid>5f98f241-bf1f-4f85-82dd-d58a508bdfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Update 
                    </value>
      <webElementGuid>7ae1e56c-e050-4d08-8383-ad8310d49d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;console&quot;)/div[@class=&quot;endpoints&quot;]/ul[1]/li[8]</value>
      <webElementGuid>9b3392ec-a578-4f79-940e-d277b5b41efc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='console']/div/ul/li[8]</value>
      <webElementGuid>c52046ea-b97e-4f83-8b5b-2d2f320cdf75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/following::li[1]</value>
      <webElementGuid>f0dcdcc3-f786-404b-87cb-abf21c421e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single &lt;resource> not found'])[1]/following::li[2]</value>
      <webElementGuid>dd692ac1-5483-46ee-bafe-41a19cbc7498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[2]/preceding::li[1]</value>
      <webElementGuid>2effb4ac-2c00-4b24-b192-6d564defe737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>e2033904-82a9-4692-be86-e81a9f2f228f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                         Update 
                    ' or . = '
                         Update 
                    ')]</value>
      <webElementGuid>af0fa132-866f-4118-9f62-612824d1eaaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
