<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_apiusers2</name>
   <tag></tag>
   <elementGuidId>286a114d-1bc3-43d7-982b-4b56ffc46680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89cb0ae5-919f-412a-95cb-5e7761d870ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>31118a64-9705-4f98-b8df-962c4d78847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>2b95c633-3d1b-4273-9aae-4b732390c42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/api/users/2</value>
      <webElementGuid>bdf60fbb-7185-41e6-8ba8-d0b92df92af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;console&quot;)/div[@class=&quot;output&quot;]/div[@class=&quot;request&quot;]/p[@class=&quot;request-title&quot;]/strong[1]/a[@class=&quot;link try-link&quot;]/span[@class=&quot;url&quot;]</value>
      <webElementGuid>45cda202-5008-46c2-89f0-d91faccb4bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      <webElementGuid>98fa0cc9-52d6-44e2-a674-f05fee94cccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delayed response'])[1]/following::span[1]</value>
      <webElementGuid>4742cdce-489b-461f-8d43-24af7896bad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://reqres.in/#support-heading'])[1]/preceding::span[2]</value>
      <webElementGuid>e3c519b4-d361-467b-b8f0-2ee2dbb38ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/api/users/2']/parent::*</value>
      <webElementGuid>76b976eb-9b4c-4baa-884e-01bf36d95700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>02760500-dc86-4487-bf6e-9813dc3d056b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '/api/users/2' or . = '/api/users/2')]</value>
      <webElementGuid>f0d47e62-a9f7-4264-afef-ba1127ab7eb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
