<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_apiuserspage2</name>
   <tag></tag>
   <elementGuidId>64401e04-7322-4e51-b91c-2344dd2a7876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9ea80a78-0d88-481e-9119-0bf9a2d6a590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>310d6e36-5fab-4e66-9cea-cdd78ecdfa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>265cc1b0-13ed-402a-ad7f-1c98f4f3f153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/api/users?page=2</value>
      <webElementGuid>c55945d6-72ef-4ad8-ba54-dcaffa8c3ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;console&quot;)/div[@class=&quot;output&quot;]/div[@class=&quot;request&quot;]/p[@class=&quot;request-title&quot;]/strong[1]/a[@class=&quot;link try-link&quot;]/span[@class=&quot;url&quot;]</value>
      <webElementGuid>0ecc2dba-2770-42f3-89e1-331bbb5420ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      <webElementGuid>bf2b4505-1c9f-4548-a1f8-1818766629f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delayed response'])[1]/following::span[1]</value>
      <webElementGuid>dd7d2149-f687-4fd7-8f40-33a8278ace68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://reqres.in/#support-heading'])[1]/preceding::span[2]</value>
      <webElementGuid>87fb0656-f06f-4ed9-980d-2df2e2566e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/api/users?page=2']/parent::*</value>
      <webElementGuid>4b4153f2-1e0f-42ae-b380-6685e2a09ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>5b21ee0a-0d2b-4d3c-931e-bfcb4cb25fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '/api/users?page=2' or . = '/api/users?page=2')]</value>
      <webElementGuid>5b4218ae-4db4-4e8e-b28a-74763619a516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
