<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_apiregister</name>
   <tag></tag>
   <elementGuidId>e2ab1b82-d6af-478a-bdee-a6e8a3d00b46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>33772143-70d2-4bbd-a975-9feb2ed78d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>b49e102a-1ab0-4edf-b2ab-297f923ea27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>c5b7947f-2aca-4284-bb16-7412a9f015aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/api/register</value>
      <webElementGuid>c0a2d4d8-f58f-4b7b-93da-65457a65cbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;console&quot;)/div[@class=&quot;output&quot;]/div[@class=&quot;request&quot;]/p[@class=&quot;request-title&quot;]/strong[1]/a[@class=&quot;link try-link&quot;]/span[@class=&quot;url&quot;]</value>
      <webElementGuid>5b5e02d8-4ba8-4ff0-83d5-8d7386252744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      <webElementGuid>51e9dd36-fedb-423b-a728-839263bec9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delayed response'])[1]/following::span[1]</value>
      <webElementGuid>8529714e-f961-449d-8738-9609b73889d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'email', '&quot;', ':')])[1]/preceding::span[1]</value>
      <webElementGuid>df7d1922-f1b3-46fd-a22b-b620ee27df7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/api/register']/parent::*</value>
      <webElementGuid>5f8d82b0-282a-44e1-8849-9a901d925adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>e0e2fdf6-9c3f-4f93-a5d8-6022dfb0b790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '/api/register' or . = '/api/register')]</value>
      <webElementGuid>9d1dce6c-8815-4459-90d8-df13c1742c53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
